[FIX] hr_employee_calendar_planning: Avoid error in post_init_hook with leaves that do not already exist
Example use case:
- Install hr_holidays
- Install hr_employee_calendar_planning

odoo.exceptions.CacheMiss: 'resource.calendar.leaves(44,).resource_id'

odoo.exceptions.MissingError: Record does not exist or has been deleted.
(Record: resource.calendar.leaves(44,), User: 1)